const previewMode = new URLSearchParams(globalThis.location?.search || "").get("preview") === "1";

export const config = Object.freeze({
  mode: previewMode ? "sample" : "live",
  sampleDataPath: "./data/sample.json?v=phase5-library-1",
  apiRoutes: Object.freeze({
    articles: "/api/articles",
    article: "/api/article",
    analyze: "/api/analyze",
    explain: "/api/explain",
    word: "/api/word",
    import: "/api/import",
    related: "/api/related",
    clientConfig: "/api/client-config",
  }),
  sampleDelayMs: 450,
  activeSourceIds: Object.freeze(["the-paper", "stcn", "jiemian"]),
  candidateLimitPerSource: 10,
  displayedResultLimit: 5,
  learnerLevels: Object.freeze(["Intermediate", "Advanced"]),
  analysisTermCounts: Object.freeze({ Intermediate: 20, Advanced: 10 }),
  defaultLearnerLevel: "Advanced",
  defaultInterests: Object.freeze([
    "人工智能",
    "中国科技",
    "商业与经济",
    "政策",
    "创业",
    "中美关系",
  ]),
  maximumArticleCharacters: 30000,
  maximumSentenceCharacters: 500,
  requestTimeoutMs: 10000,
  analysisRequestTimeoutMs: 45000,
  importRequestTimeoutMs: 25000,
  relatedReadingRequestTimeoutMs: 45000,
  driveRequestTimeoutMs: 15000,
  googleIdentityScriptUrl: "https://accounts.google.com/gsi/client",
  googleDriveApiBaseUrl: "https://www.googleapis.com/drive/v3",
  googleDriveUploadBaseUrl: "https://www.googleapis.com/upload/drive/v3",
  googleDriveScope: "https://www.googleapis.com/auth/drive.appdata",
  googleDriveFileName: "daily-chinese-read-sync.json",
  maximumDriveSyncBytes: 2000000,
  minimumImportCharacters: 180,
  maximumImportCharacters: 30000,
  storageKey: "daily-chinese-read:v1:vocabulary",
  storageVersion: 1,
  knownWordsStorageKey: "daily-chinese-read:v1:known-words",
  knownWordsStorageVersion: 1,
  savedArticlesStorageKey: "daily-chinese-read:v1:articles",
  savedArticlesStorageVersion: 1,
  driveSyncPreferenceKey: "daily-chinese-read:v1:drive-sync-enabled",
  driveSyncMetaKey: "daily-chinese-read:v1:drive-sync-meta",
  driveSyncVersion: 1,
  reviewIntervalsDays: Object.freeze([0, 1, 3, 7, 14, 30, 60, 120]),
  featureFlags: Object.freeze({
    liveRetrieval: true,
    showPreviewStates: previewMode,
    languageScaffolding: true,
    vocabulary: true,
    customArticleImport: true,
    relatedReading: true,
    savedArticles: true,
    driveSync: true,
  }),
});
