const previewMode = new URLSearchParams(globalThis.location?.search || "").get("preview") === "1";

export const config = Object.freeze({
  mode: previewMode ? "sample" : "live",
  sampleDataPath: "./data/sample.json?v=high-resolution-images-1",
  apiRoutes: Object.freeze({
    articles: "/api/articles",
    article: "/api/article",
    analyze: "/api/analyze",
    explain: "/api/explain",
    word: "/api/word",
  }),
  sampleDelayMs: 450,
  activeSourceIds: Object.freeze(["the-paper", "stcn", "jiemian"]),
  candidateLimitPerSource: 10,
  displayedResultLimit: 5,
  learnerLevels: Object.freeze(["Intermediate", "Advanced"]),
  analysisTermCounts: Object.freeze({ Intermediate: 20, Advanced: 10 }),
  defaultLearnerLevel: "Advanced",
  defaultInterests: Object.freeze([
    "人工智能",
    "中国科技",
    "商业与经济",
    "政策",
    "创业",
    "中美关系",
  ]),
  maximumArticleCharacters: 30000,
  maximumSentenceCharacters: 500,
  requestTimeoutMs: 10000,
  analysisRequestTimeoutMs: 45000,
  storageKey: "daily-chinese-read:v1:vocabulary",
  storageVersion: 1,
  knownWordsStorageKey: "daily-chinese-read:v1:known-words",
  knownWordsStorageVersion: 1,
  reviewIntervalsDays: Object.freeze([0, 1, 3, 7, 14, 30, 60, 120]),
  featureFlags: Object.freeze({
    liveRetrieval: true,
    showPreviewStates: previewMode,
    languageScaffolding: true,
    vocabulary: true,
  }),
});
